### ISSUE TITLE
netdb.h ?

### ISSUE THREAD

**Issue by Jan-E** [sirsnyder/pthreads#1]
Did you use a Windows version of netdb.h to compile https://github.com/SirSnyder/pthreads/files/838565/php_pthreads-3.1.7-beta.1-7.1-ts-vc14-x64.zip ?

The source is still dependent on it:
https://github.com/SirSnyder/pthreads/blob/master/src/pthreads.h#L41

**Comment by sirsnyder** [comment]
Sorry, i'm very busy. I will push a branch with the changes within the next days.
